import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { Toaster } from "@/ui/toaster";
import { Dashboard } from "@/common/dashboard";
import { TooltipProvider } from "@/ui/tooltip";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TooltipProvider>
      <div className={`w-full  min-h-screen  ${openSans.className}`}>
        <div className="flex w-full h-full">
          <Dashboard.Sidebar />
          <div className="flex flex-col w-full h-full ">
            <Dashboard.Navbar />
            {children}
          </div>
        </div>
        <Toaster />
      </div>
    </TooltipProvider>
  );
}
